project:
  type: website
  output-dir: docs

website:
  title: "Pablo-source.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - City_maps.qmd
      - Resources.qmd
      - NHS_R_Pycom_2023.qmd
      - Annotations.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

