---
title: "R and Python online resources"
title-block-banner: true
author: "Pablo Leon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    toc: true
    code-fold: true
---

## R

R is an open-source programming language that is widely used among statisticians and data scientists in the NHS. R has a large number of built-in functions and packages for statistical analysis and data visualisation. Along with tools such as Python1, R can be used to develop so-called reproducible analytical pipelines (RAP).

See general website for R:

- The R Project for Statistical Computing <https://www.r-project.org/> 

Quarto website: <https://quarto.org>.




## POSIT

Posit is the Company  who developed RStudio IDE among other products, previously called RStudio. All your data products have a home on Posit Connect, Deploy R & Python content easily and securely, automate code execution and deliver insights to stakeholders that need them

- Posit website: <https://posit.co/>

### POSIT learning resources

Learning materials from POSIT about R, Python and Quarto

- Blogs: <https://posit.co/blog/>
- Cheatsheets: <https://posit.co/resources/cheatsheets/>
- Videos: <https://posit.co/resources/videos/>

## RStudio

RStudio is an integrated development environment for R, a programming language for statistical computing and graphics. Developed by POSIT. It is available in two formats: RStudio Desktop is a regular desktop application while RStudio Server runs on a remote server and allows accessing RStudio using a web browser.

- RStudio IDE to run R: <https://posit.co/products/open-source/rstudio/>

## Quarto

Set of resources about Quarto:

- An Open-source scientific and technical publishing system <https://quarto.org/>
- Get Started. Install Quarto: <https://quarto.org/docs/get-started/>

### Quarto Guide

Authoring quarto documents

- Include formatted title blocks at the start of the article: <https://quarto.org/docs/authoring/title-blocks.html>
- Update the date automatically 
<https://bookdown.org/yihui/rmarkdown-cookbook/update-date.html>

## Python

Set of resources about Python

- Python<https://www.python.org>

- Python wiki page with Python for Programmers: <https://wiki.python.org/moin/BeginnersGuide/Programmers>



https://www.python.org/downloads/

## NHS-R Community

Together we aim to promote the use of R in the NHS <https://nhsrcommunity.com/>

Events

1. Conferences
- Upcoming conferences: <https://nhsrcommunity.com/events/#event_type-conferences>
- Show Past Events: <https://nhsrcommunity.com/past-events/>

1.1 NHS-R Community Conference 2022
<https://nhsrcommunity.com/events/nhs-r-community-conference-2022/>

2. Group Discussion

3. Group Discussion/workshops

4. Webinars
<https://nhsrcommunity.com/events/#event_type-webinars>

5. Workshops
<https://nhsrcommunity.com/events/#event_type-workshops>


## Code editors

## YouTube videos

Collection of interesting Youtube videos



## Online resources to learn Python and R

## Python

### Beginners GUide

Python Beginners Guide: <https://wiki.python.org/moin/BeginnersGuide/Programmers>
The Python Tutorial: <https://docs.python.org/3/tutorial/index.html>
